### ISSUE TITLE
Adding an alternative to Promise.all that allow failures

### ISSUE THREAD

**Issue by nicolocarpignoli** [chialab/proteins#10]
This function is very useful in case someone wants to have the behaviour of Promise.all without a negative response if some of the promises fails.

```
function allSkippingErrors(promises) {
  return Promise.all(
    promises.map(p => p.catch(error => null))
  )
}
```

I'm asking if `proteins` is the right place for such an helper. Thanks to @DarioSacco for the idea.

**Comment by edoardocavazza** [comment]
Is [`Promise.allSettled`](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Promise/allSettled) what are you looking for?

**Comment by nicolocarpignoli** [comment]
exactly @edoardocavazza. we can wait :)

**Comment by edoardocavazza** [comment]
Since this feature became part of the ECMAScript spec, I think we could use a polyfill instead!
