### ISSUE TITLE
keypath gives an 'invalid scope' error for Event object

### ISSUE THREAD

**Issue by nicolocarpignoli** [Chialab/proteins#4]
At the moment keypath gives an `invalid scope` error for objects (as first parameter) that doesn't pass `isObject` check of `proteins`. This could be a tight solution that can limit the use of `keypath` with useful object such as javascript's `Event` object.

**Comment by edoardocavazza** [comment]
At the moment, the check for valid scope is:
https://github.com/Chialab/proteins/blob/master/src/keypath.js#L22
which handles arrays and plain objects.

A better approach could be to check if the value can handle properties, which transpiled in js is: `!isFalsy(val) && typeof val === 'object'` (remember that `typeof null` is `'object'` 🤕). 

What do you think @nicolocarpignoli ?

**Comment by nicolocarpignoli** [comment]
I'm looking forward to this and I will open a PR starting from your suggestion ;)
